# Generated by Django 6.0.5 on 2026-06-04 09:18

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trips', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('event_type', models.CharField(choices=[('delay', 'Delay'), ('breakdown', 'Breakdown'), ('fuel', 'Fuel'), ('sos', 'SOS'), ('note', 'Note')], max_length=12)),
                ('notes', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('driver', models.ForeignKey(limit_choices_to={'role': 'driver'}, on_delete=django.db.models.deletion.PROTECT, related_name='driver_logs', to=settings.AUTH_USER_MODEL)),
                ('trip', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='driver_logs', to='trips.trip')),
            ],
            options={
                'db_table': 'driver_logs',
                'ordering': ('-created_at',),
                'get_latest_by': 'created_at',
                'abstract': False,
                'indexes': [models.Index(fields=['driver', '-timestamp'], name='driver_logs_driver__e66f98_idx')],
            },
        ),
    ]
