# Generated by Django 6.0.5 on 2026-06-02 08:13

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=120)),
                ('polyline_json', models.JSONField(blank=True, default=list)),
                ('estimated_duration', models.PositiveIntegerField(help_text='Baseline duration in minutes.')),
                ('color', models.CharField(max_length=7, validators=[django.core.validators.RegexValidator(code='invalid_color', message='Enter a valid hex colour, e.g. #1E88E5.', regex='^#(?:[0-9a-fA-F]{3}|[0-9a-fA-F]{6})$')])),
            ],
            options={
                'db_table': 'routes',
                'ordering': ('-created_at',),
                'get_latest_by': 'created_at',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('plate', models.CharField(max_length=20)),
                ('capacity', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('idle', 'Idle'), ('maintenance', 'Maintenance'), ('retired', 'Retired')], default='idle', max_length=12)),
                ('assigned_driver', models.ForeignKey(blank=True, limit_choices_to={'role': 'driver'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_buses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'buses',
                'ordering': ('-created_at',),
                'get_latest_by': 'created_at',
                'abstract': False,
                'indexes': [models.Index(fields=['status'], name='buses_status_07a312_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('plate',), name='uniq_bus_plate_active')],
            },
        ),
        migrations.CreateModel(
            name='BusStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=120)),
                ('lat', models.DecimalField(decimal_places=6, max_digits=9)),
                ('lng', models.DecimalField(decimal_places=6, max_digits=9)),
                ('sequence', models.PositiveIntegerField(help_text='Order along the route.')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stops', to='buses.route')),
            ],
            options={
                'db_table': 'bus_stops',
                'ordering': ('route', 'sequence'),
                'get_latest_by': 'created_at',
                'indexes': [models.Index(fields=['route', 'sequence'], name='bus_stops_route_i_b71286_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('route', 'sequence'), name='uniq_busstop_route_sequence_active')],
            },
        ),
    ]
