# Generated by Django 6.0.5 on 2026-06-04 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='fare',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
