# Generated by Django 6.0.5 on 2026-06-04 05:20

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buses', '0002_route_fare'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='fare',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
    ]
