# Generated by Django 6.0.5 on 2026-06-05 05:34

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('buses', '0003_alter_route_fare'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('service_type', models.CharField(max_length=120)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('serviced_at', models.DateTimeField()),
                ('next_due', models.DateField(blank=True, null=True)),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='maintenance_logs', to='buses.bus')),
            ],
            options={
                'db_table': 'maintenance_logs',
                'ordering': ('-created_at',),
                'get_latest_by': 'created_at',
                'abstract': False,
                'indexes': [models.Index(fields=['bus', '-serviced_at'], name='maintenance_bus_id_ec3169_idx')],
            },
        ),
    ]
