# Generated by Django 6.0.5 on 2026-06-04 05:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
        ('trips', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='ticket',
            name='uniq_ticket_qr_code_active',
        ),
        migrations.AddConstraint(
            model_name='ticket',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False), models.Q(('qr_code', ''), _negated=True)), fields=('qr_code',), name='uniq_ticket_qr_code_active'),
        ),
    ]
